variables:
    # path to remote docker image, e.g. registry.zjvis.org/zjvis/continuous-integration-demo
    IMAGE: $CI_REGISTRY_IMAGE
    VERSION: '0.0.1'
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''

services:
    # add a docker engine service for building docker images
    - name: docker:dind
      command:
          - 'dockerd-entrypoint.sh'
          - '--registry-mirror'
          - 'https://vydcbpdf.mirror.aliyuncs.com'
          #   - 'https://dockerhub.azk8s.cn' # Use azure k8s mirror
stages:
    - install
    - build
    - deploy

# Lint and build test.
install:
    stage: install
    image: node:10
    allow_failure: false
    cache:
        key: cache-key
        paths:
            - docs/
    script:
        - git config --global url."https://${GITLAB_DEPLOY_USER}:${GITLAB_DEPLOY_TOKEN}@git.zjvis.org/".insteadOf "https://git.zjvis.org/"
        - npm config set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass -g
        - npm install --registry=https://registry.npm.taobao.org
        - npm run build

build:
    stage: build
    image: docker
    allow_failure: false
    cache:
        key: cache-key
        paths:
            - docs/
    variables:
        DOCKER_HOST: tcp://localhost:2375
    before_script:
        - docker info
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $IMAGE || true
    script:
        - docker build --cache-from $IMAGE:latest -t $IMAGE .
        - docker push $IMAGE

deploy:
    stage: deploy
    image: lachlanevenson/k8s-kubectl
    allow_failure: false
    environment:
        name: production
    script:
        - sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories && apk update --no-cache && apk add gettext curl
        - kubectl -n $KUBE_NAMESPACE create secret docker-registry ${CI_PROJECT_NAME}-pull-secret --docker-server="$CI_REGISTRY" --docker-username="$GITLAB_DEPLOY_USER" --docker-password="$GITLAB_DEPLOY_TOKEN" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run | kubectl apply -f -
        - envsubst < deployment.yaml | kubectl apply -f -
